# Generated by Django 4.2.8 on 2023-12-12 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhood', '0002_business_bs_image_neighborhood_hood_pic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='bs_image',
        ),
        migrations.RemoveField(
            model_name='neighborhood',
            name='hood_pic',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
    ]
